#! python
'''
Created on 25.06.2011

@author: niko
'''
import datetime
import logging
from optparse import OptionParser

from parlisscraper.exporters.CSVExporter import CSVExporter
from parlisscraper.indexfinder import ParlisIndexFinder
from parlisscraper.scraper import ParlisScraper

LOGGER = logging.getLogger('parlisscraper')


def startWorkflow(startYear=None, endYear=None, onlySearchIndexes=False,
                  onlyScrapeFiles=False, exportLimit=None):
    if startYear is None:
        startYear = 1992

    if endYear is None:
        endYear = datetime.date.today().year

    for year in range(startYear, endYear + 1):
        LOGGER.info("Processing year {0}".format(year))

        if not onlyScrapeFiles:
            indexer = ParlisIndexFinder(year)
        else:
            indexer = open('{year}-IDlist.txt'.format(year=year))

        if not onlySearchIndexes:
            scraper = ParlisScraper(year, indexer)

            csvExporter = CSVExporter("{0}-antraege.csv".format(year),
                                      exportLimit)
            csvExporter.createExport(scraper)
        else:
            with open('{year}-IDlist.txt'.format(year=year), "w") as output:
                for documentId in indexer:
                    output.write('{id}\n'.format(id=documentId))


if __name__ == '__main__':
    optionParser = OptionParser()
    optionParser.add_option('-s', '--startYear', dest='startYear', type=int,
                            default=1992,
                            help='The year from which one the scraping starts')
    optionParser.add_option('-e', '--endYear', dest='endYear', type=int,
                            default=None,
                            help='The year to which the scraping will work')
    optionParser.add_option('-i', '--onlyIndexes', dest='onlyIndexes',
                            default=False, action="store_true",
                            help='Only create index files.')
    optionParser.add_option('-d', '--onlyScraping', dest='onlyScraping',
                            default=False, action="store_true",
                            help='Only scrape webpages.')
    optionParser.add_option('--debug', action="store_true", default=False,
                            help="Enable debug output.")
    optionParser.add_option('--verbose', action="store_true", default=False,
                            help="Verbose output.")
    optionParser.add_option('--export-limit', dest='exportLimit', type=int,
                            default=0,
                            help='Limit the number of entries in the export')

    (options, unparseableArguments) = optionParser.parse_args()

    if options.debug:
        logging.basicConfig(level=logging.DEBUG)
    elif options.verbose:
        logging.basicConfig(level=logging.INFO)
    else:
        logging.basicConfig(level=logging.ERROR)

    startWorkflow(options.startYear, options.endYear,
                  options.onlyIndexes, options.onlyScraping,
                  options.exportLimit)
